#!/bin/bash
set -e

# Note: we don't just use "apache2ctl" here because it itself is just a shell-script wrapper around apache2 which provides extra functionality like "apache2ctl start" for launching apache2 in the background.
# (also, when run as "apache2ctl <apache args>", it does not use "exec", which leaves an undesirable resident shell process)

: "${APACHE_CONFDIR:=/etc/apache2}"
: "${APACHE_ENVVARS:=$APACHE_CONFDIR/envvars}"
if test -f "$APACHE_ENVVARS"; then
	. "$APACHE_ENVVARS"
fi

# Apache gets grumpy about PID files pre-existing
: "${APACHE_RUN_DIR:=/var/run/apache2}"
: "${APACHE_PID_FILE:=$APACHE_RUN_DIR/apache2.pid}"
rm -f "$APACHE_PID_FILE"

# create missing directories
# (especially APACHE_RUN_DIR, APACHE_LOCK_DIR, and APACHE_LOG_DIR)
for e in "${!APACHE_@}"; do
	if [[ "$e" == *_DIR ]] && [[ "${!e}" == /* ]]; then
		# handle "/var/lock" being a symlink to "/run/lock", but "/run/lock" not existing beforehand, so "/var/lock/something" fails to mkdir
		#   mkdir: cannot create directory '/var/lock': File exists
		dir="${!e}"
		while [ "$dir" != "$(dirname "$dir")" ]; do
			dir="$(dirname "$dir")"
			if [ -d "$dir" ]; then
				break
			fi
			absDir="$(readlink -f "$dir" 2>/dev/null || :)"
			if [ -n "$absDir" ]; then
				mkdir -p "$absDir"
			fi
		done

		mkdir -p "${!e}"
	fi
done

#exec /bin/bash -c 'php-fpm -D && nginx -g '"'"'daemon off;'"'"' "$@"'
#exec apache2 -DFOREGROUND "$@"
sed -E -i -e 's@(<argument name="tableStrategy" xsi:type="object">Magento\\Catalog\\Model\\ResourceModel\\Product\\Indexer\\TemporaryTableStrategy</argument>)@<argument name="tableStrategy" xsi:type="object">Magento\\Framework\\Indexer\\Table\\Strategy</argument>@g' /var/www/html/magento2/vendor/magento/module-catalog/etc/di.xml
sed -E -i -e 's@(<argument name="tableStrategy" xsi:type="object">Magento\\Catalog\\Model\\ResourceModel\\Product\\Indexer\\TemporaryTableStrategy</argument>)@<argument name="tableStrategy" xsi:type="object">Magento\\Framework\\Indexer\\Table\\Strategy</argument>@g' /var/www/html/magento2/vendor/magento/module-configurable-product/etc/di.xml
sed -E -i -e 's@(<argument name="tableStrategy" xsi:type="object">Magento\\Catalog\\Model\\ResourceModel\\Product\\Indexer\\TemporaryTableStrategy</argument>)@<argument name="tableStrategy" xsi:type="object">Magento\\Framework\\Indexer\\Table\\Strategy</argument>@g' /var/www/html/magento2/vendor/magento/module-bundle/etc/di.xml
sed -E -i -e 's@(<argument name="tableStrategy" xsi:type="object">Magento\\Catalog\\Model\\ResourceModel\\Product\\Indexer\\TemporaryTableStrategy</argument>)@<argument name="tableStrategy" xsi:type="object">Magento\\Framework\\Indexer\\Table\\Strategy</argument>@g' /var/www/html/magento2/vendor/magento/module-downloadable/etc/di.xml

#sed -i -e 's@listen = 127.0.0.1:9000@listen = /var/run/php7.3-fpm.sock@g' /usr/local/etc/php-fpm.d/www.conf
#sed -i -e 's@listen = 9000@;listen = 9000@g' /usr/local/etc/php-fpm.d/zz-docker.conf
#sed -i -e 's@listen = 9000@listen = /var/run/php7.3-fpm.sock@g' /usr/local/etc/php-fpm.d/zz-docker.conf

rm /etc/apache2/sites-enabled/000-default.conf

# Fix access rights to stdout and stderr
# chown magento:www-data /proc/self/fd/{1,2}
# usermod -a -G root magento
# usermod -a -G root www-data

exec /bin/bash -c 'php-fpm -D && apache2 -DFOREGROUND '"$@"
#exec /bin/bash -c 'php-fpm -D && chown magento:www-data /var/run/php7.3-fpm.sock && apache2 -DFOREGROUND '"$@"
#exec /bin/bash -c 'su - magento -c '"'"'/usr/local/sbin/php-fpm -D && /usr/sbin/apache2 -DFOREGROUND '"'""$@"
