FROM alpine:3.10

RUN apk --no-cache --update --virtual runtime-deps add varnish
CMD /bin/sh -c 'varnishd \
                -s malloc,1G \
                -a :80 \
                -f /etc/varnish/magento.vcl && varnishlog -q "RespStatus >= 400 or BerespStatus >= 400"'
