FROM mytestmagentocr.azurecr.io/magento:latest

USER root
COPY setup-magento.sh /setup-magento.sh
#COPY auth.json /home/magento/.composer/auth.json
RUN chown magento:www-data /setup-magento.sh && \
    #chown magento:www-data /home/magento/.composer/auth.json && \
    chown -R www-data:www-data /var/www && \
    chmod go-rwx /var/www && \
    chmod go+x /var/www && \
    chgrp -R www-data /var/www && \
    chmod -R go-rwx /var/www && \
    chmod -R g+rx /var/www && \
    chmod -R g+rwx /var/www
WORKDIR /var/www
ENTRYPOINT ["/setup-magento.sh"]
CMD ["/bin/sh"]
