kind: Deployment
apiVersion: apps/v1
metadata:
  name: magentoweb
  namespace: magento2
  labels:
    app: magentoweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magentoweb
  template:
    metadata:
      labels:
        app: magentoweb
    spec:
      containers:
      #- image: magetoperftestcr.azurecr.io/magento2-fpm:1.1
      #- image: magentonfscr.azurecr.io/magento2-fpm:1.1
      #- image: magentonfscr.azurecr.io/magento2-fpm:1.3
      #- image: magentonfscr.azurecr.io/magento2-fpm:1.4
      - image: magentonfscr.azurecr.io/magento2-fpm:1.5
        imagePullPolicy: Always
        name: magentoweb
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            memory: "2Gi"
        volumeMounts:
          - name: magento-config
            mountPath: /var/www/html/magento2/app/etc/config.php
            subPath: config.php
          - name: apache-config
            mountPath: /etc/apache2/sites-available/magento.conf
            subPath: magento.conf
          - name: magento-env
            mountPath: /var/www/html/magento2/app/etc/env.php
            subPath: env.php
          - name: www-conf
            mountPath: /usr/local/etc/php-fpm.d/www.conf
            subPath: www.conf
          - name: magento-pub-media 
            mountPath: /var/www/html/magento2/pub/media
          - name: magento-pub-static
            mountPath: /var/www/html/magento2/pub/static
          - name: magento
            mountPath: /mnt/magento
          # - name: magento-af
          #   mountPath: /mnt/magento-af
          - name: magento-pub-media-af
            mountPath: /mnt/magento-af-media
          - name: magento-pub-static-af
            mountPath: /mnt/magento-af-static
      imagePullSecrets:
      - name: magento-registry-cred
      volumes:
      - name: magento-config
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento
      - name: apache-config
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento
      - name: magento-env
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento
      - name: magento-nginx-config
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento
      - name: nginx-mime-types
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento
      - name: www-conf
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento
      - name: magento-pub-media-af
        azureFile:
          secretName: magentonfsfs-secret
          shareName: magento-large/media
          readOnly: false
      - name: magento-pub-static-af
        azureFile:
          secretName: magentonfsfs-secret
          shareName: magento-large/static
          readOnly: false
      - name: magento-pub-media
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento/pub/media
      - name: magento-pub-static
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento/pub/static
      - name: magento
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento
      # - name: magento-af
      #   persistentVolumeClaim:
      #     claimName: magento-azurefile-nfs-pvc
      # - name: magento-af
      #   nfs:
      #     server: magentoazurefilesnfs.privatelink.file.core.windows.net
      #     path: /magentoazurefilesnfs/magentonfs
      #     mountOptions:
      #       - vers=4
      #       - minorversion=1
      #       - proto=tcp
      #       - port=2049
      #       - sec=sys