kind: Deployment
apiVersion: apps/v1
metadata:
  name: magentoweb
  namespace: magento2
  labels:
    app: magentoweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magentoweb
  template:
    metadata:
      labels:
        app: magentoweb
    spec:
      containers:
      #- image: magetoperftestcr.azurecr.io/magento2-fpm:1.1
      #- image: magentonfscr.azurecr.io/magento2-fpm:1.1
      - image: magentonfscr.azurecr.io/magento2-fpm:1.3
        imagePullPolicy: Always
        name: magentoweb
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            memory: "2Gi"
        volumeMounts:
          - name: magento-config
            mountPath: /var/www/html/magento2/app/etc/config.php
            subPath: config.php
          - name: magento-env
            mountPath: /var/www/html/magento2/app/etc/env.php
            subPath: env.php
          - name: php-ini
            mountPath: /usr/local/etc/php/php.ini
            subPath: php.ini
          # - name: magento-nginx-config
          #   mountPath: /etc/nginx/sites-enabled/magento.nginx.conf
          #   subPath: magento.nginx.conf
          # - name: nginx-mime-types
          #   mountPath: /etc/nginx/mime.types
          #   subPath: mime.types
          - name: www-conf
            mountPath: /usr/local/etc/php-fpm.d/www.conf
            subPath: www.conf
          - name: magento-pub-media 
            mountPath: /var/www/html/magento2/pub/media
          - name: magento-pub-static
            mountPath: /var/www/html/magento2/pub/static
          - name: magento
            mountPath: /mnt/magento
      # - image: ACR_LOGIN_SERVER/varnish:latest
      #   imagePullPolicy: Always
      #   name: magentoweb
      #   ports:
      #   - containerPort: 80
      #     protocol: TCP
      #   resources:
      #     requests:
      #       memory: "2Gi"
      imagePullSecrets:
      - name: magento-registry-cred
      # securityContext:
      #   fsGroup: 82
      volumes:
      - name: magento-config
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento
      - name: magento-env
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento
      # - name: magento-nginx-config
      #   nfs:
      #     server: magento-nfs-vm
      #     path: /export/magento-storage-pool/magento
      # - name: nginx-mime-types
      #   nfs:
      #     server: magento-nfs-vm
      #     path: /export/magento-storage-pool/magento
      - name: www-conf
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento
      - name: php-ini
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento
      - name: magento-pub-media
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento/pub/media
      - name: magento-pub-static
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento/pub/static
      - name: magento
        nfs:
          server: magento-nfs-vm
          path: /export/magento-storage-pool/magento
        # secret:
        #   secretName: magento-config
      # - name: magento-pub-media
      #   azureFile:
      #     secretName: azurefilecreds
      #     shareName: magento2/media
      #     readOnly: false
      # - name: magento-pub-static
      #   azureFile:
      #     secretName: azurefilecreds
      #     shareName: magento2/static
      #     readOnly: false

