kind: Deployment
apiVersion: apps/v1
metadata:
  name: magentoweb
  namespace: default
  labels:
    app: magentoweb
spec:
  replicas: 10
  selector:
    matchLabels:
      app: magentoweb
  template:
    metadata:
      labels:
        app: magentoweb
    spec:
      containers:
      - image: ACR_LOGIN_SERVER/magento2:latest
        imagePullPolicy: Always
        name: magentoweb2
        resources:
          requests:
            memory: "2Gi"
        volumeMounts:
          - name: magento-pub-media 
            mountPath: /var/www/html/magento2/pub/media
          - name: magento-pub-static
            mountPath: /var/www/html/magento2/pub/static
          - name: magento-config
            mountPath: /var/www/html/magento2/app/etc/env.php
            subPath: env.php
      - image: ACR_LOGIN_SERVER/varnish:latest
        imagePullPolicy: Always
        name: magentoweb
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "2Gi"
      imagePullSecrets:
      - name: magento-registry-cred
      securityContext:
        fsGroup: 82
      volumes:
      - name: magento-config
        secret:
          secretName: magento-config
      - name: magento-pub-media
        azureFile:
          secretName: azurefilecreds
          shareName: pub/media
          readOnly: false
      - name: magento-pub-static
        azureFile:
          secretName: azurefilecreds
          shareName: pub/static
          readOnly: false

